# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
data:
  username: amVldC11c2Vy  # Replace with your Base64-encoded username
  password: amVldC1wYXNz  # Replace with your Base64-encoded password
